#!/usr/bin/env perl 

use strict; use warnings;


use lib 'lib';
use AnsibleModule;

my $module=AnsibleModule->new(argument_spec=>{hello => {}});
my $params=$module->params;
$params->{msg}='echo';

$module->exit_json($params);
